# docker-compose.yml
# docker compose build
# docker-compose --env-file .ENV up -d
# Getting into the container: docker exec -it facescore bash

version: '2'
services:
  database:
    image: postgres:14
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    container_name: "database"
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
